version: '3.1'


volumes:
  db-data:

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./site:/usr/share/nginx/html

  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  tgbot:
    container_name: bot
    build:
      context: ./bot
    volumes: 
      - ./bot:/bot
    command: python app.py
    restart: always
    env_file:
      - "./bot/.env"
    depends_on:
      - db
